spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.defer-datasource-initialization=false

logging.level.com.edu.sistema_inventario=${LOG_LEVEL_APP:INFO}
logging.level.org.springframework.security=${LOG_LEVEL_SECURITY:WARN}

jwt.secret=${JWT_SECRET}

spring.h2.console.enabled=false
springdoc.swagger-ui.enabled=false

app.security.dev-tools-enabled=false
